import Header from '@/components/Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'IMDb Clone',
  description: 'Generated by create next app',
  content: 'width=device-width',
  description: 'This is IMDb clone website.',
  link: 'href="/dist/output.css" rel="stylesheet'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* HEADER */}
        <Header/>
        {children}
      </body>
    </html>
  )
}
